### ISSUE TITLE
Dependabot fails in an Elixir umbrella app contained in a monorepo

### ISSUE THREAD

**Issue by scohen** [dependabot/feedback#787]
Hi! 
I added dependabot to my project which is a monorepo with the following structure:
```
/api
  mix.exs
  /apps
    /app_1
    /app_2
/ui
  config.json
```
I then received the following in an issue:
```
Dependabot can't evaluate your Elixir dependency files.

As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.

The error Dependabot encountered was:
** (File.Error) could not list directory "./apps": no such file or directory
    (elixir) lib/file.ex:1572: File.ls!/1
    mix.exs:58: SonatoOs.MixProject.docs/0
    mix.exs:10: SonatoOs.MixProject.project/0
    (mix) lib/mix/project.ex:740: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:114: Mix.Project.push/3
    (stdlib) lists.erl:1263: :lists.foldl/3

{"error":""}
```

From what I can tell, it's running its dependency analysis from the root level, but all the elixir sub-projects live in `api/apps`

**Comment by feelepxyz** [comment]
Moving to email ticket.
