### ISSUE TITLE
Dependabot is failing when installing rtree because missing libspatialindex

### ISSUE THREAD

**Issue by bryanculbertson** [dependabot/feedback#792]
> OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory

```
updater | ERROR <job_17271076> Command errored out with exit status 1:
updater | <job_17271076>  command: /usr/local/.pyenv/versions/3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/tmp4gluod60build/rtree/setup.py'"'"'; __file__='"'"'/tmp/tmp4gluod60build/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/tmp4gluod60build/rtree/pip-egg-info
updater | <job_17271076>      cwd: /tmp/tmp4gluod60build/rtree/
updater | <job_17271076> Complete output (13 lines):
updater | <job_17271076> Traceback (most recent call last):
updater | <job_17271076>   File "<string>", line 1, in <module>
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/setup.py", line 3, in <module>
updater | <job_17271076>     import rtree
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/__init__.py", line 1, in <module>
updater | <job_17271076>     from .index import Rtree
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/index.py", line 6, in <module>
updater | <job_17271076>     from . import core
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/core.py", line 107, in <module>
updater | <job_17271076>     rt = ctypes.CDLL(lib_name)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 364, in __init__
updater | <job_17271076>     self._handle = _dlopen(self._name, mode)
updater | <job_17271076> OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory
updater | <job_17271076> ----------------------------------------
updater | <job_17271076> Traceback (most recent call last):
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/bin/pip-compile", line 10, in <module>
updater | <job_17271076>     sys.exit(cli())
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 764, in __call__
updater | <job_17271076>     return self.main(*args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 717, in main
updater | <job_17271076>     rv = self.invoke(ctx)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 956, in invoke
updater | <job_17271076>     return ctx.invoke(self.callback, **ctx.params)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
updater | <job_17271076>     return callback(*args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
updater | <job_17271076>     return f(get_current_context(), *args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/scripts/compile.py", line 359, in cli
updater | <job_17271076>     results = resolver.resolve(max_rounds=max_rounds)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 168, in resolve
updater | <job_17271076>     has_changed, best_matches = self._resolve_one_round()
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
updater | <job_17271076>     their_constraints.extend(self._iter_dependencies(best_match))
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 358, in _iter_dependencies
updater | <job_17271076>     dependencies = self.repository.get_dependencies(ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/local.py", line 70, in get_dependencies
updater | <job_17271076>     return self.repository.get_dependencies(ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 269, in get_dependencies
updater | <job_17271076>     download_dir, ireq, wheel_cache
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 225, in resolve_reqs
updater | <job_17271076>     results = resolver._resolve_one(reqset, ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
updater | <job_17271076>     abstract_dist = self._get_abstract_dist_for(req_to_install)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
updater | <job_17271076>     req, self.session, self.finder, self.require_hashes
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
updater | <job_17271076>     req, self.req_tracker, finder, self.build_isolation,
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
updater | <job_17271076>     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
updater | <job_17271076>     self.req.prepare_metadata()
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
updater | <job_17271076>     self.metadata_directory = metadata_generator(self)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
updater | <job_17271076>     command_desc='python setup.py egg_info',
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
updater | <job_17271076>     raise InstallationError(exc_msg)
updater | <job_17271076> pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bryanculbertson** [comment]
I upgrade to `rtree` `0.9.3` and now the error is:
```
updater | <job_17502186>  command: /usr/local/.pyenv/versions/3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/tmpx5wvp_tjbuild/rtree/setup.py'"'"'; __file__='"'"'/tmp/tmpx5wvp_tjbuild/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/tmpx5wvp_tjbuild/rtree/pip-egg-info
updater | <job_17502186>      cwd: /tmp/tmpx5wvp_tjbuild/rtree/
updater | <job_17502186> Complete output (15 lines):
updater | <job_17502186> Traceback (most recent call last):
updater | <job_17502186>   File "<string>", line 1, in <module>
updater | <job_17502186>   File "/tmp/tmpx5wvp_tjbuild/rtree/setup.py", line 3, in <module>
updater | <job_17502186>     import rtree
updater | <job_17502186>   File "/tmp/tmpx5wvp_tjbuild/rtree/rtree/__init__.py", line 1, in <module>
updater | <job_17502186>     from .index import Rtree
updater | <job_17502186>   File "/tmp/tmpx5wvp_tjbuild/rtree/rtree/index.py", line 6, in <module>
updater | <job_17502186>     from . import core
updater | <job_17502186>   File "/tmp/tmpx5wvp_tjbuild/rtree/rtree/core.py", line 145, in <module>
updater | <job_17502186>     rt.Error_GetLastErrorNum.restype = ctypes.c_int
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
updater | <job_17502186>     func = self.__getitem__(name)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
updater | <job_17502186>     func = self._FuncPtr((name_or_ordinal, self))
updater | <job_17502186> AttributeError: /usr/local/.pyenv/versions/3.7.5/bin/python3.7: undefined symbol: Error_GetLastErrorNum
updater | <job_17502186> ----------------------------------------
updater | <job_17502186> Traceback (most recent call last):
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/bin/pip-compile", line 10, in <module>
updater | <job_17502186>     sys.exit(cli())
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 764, in __call__
updater | <job_17502186>     return self.main(*args, **kwargs)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 717, in main
updater | <job_17502186>     rv = self.invoke(ctx)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 956, in invoke
updater | <job_17502186>     return ctx.invoke(self.callback, **ctx.params)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
updater | <job_17502186>     return callback(*args, **kwargs)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
updater | <job_17502186>     return f(get_current_context(), *args, **kwargs)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/scripts/compile.py", line 359, in cli
updater | <job_17502186>     results = resolver.resolve(max_rounds=max_rounds)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 168, in resolve
updater | <job_17502186>     has_changed, best_matches = self._resolve_one_round()
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
updater | <job_17502186>     their_constraints.extend(self._iter_dependencies(best_match))
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 358, in _iter_dependencies
updater | <job_17502186>     dependencies = self.repository.get_dependencies(ireq)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/local.py", line 70, in get_dependencies
updater | <job_17502186>     return self.repository.get_dependencies(ireq)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 269, in get_dependencies
updater | <job_17502186>     download_dir, ireq, wheel_cache
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 225, in resolve_reqs
updater | <job_17502186>     results = resolver._resolve_one(reqset, ireq)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
updater | <job_17502186>     abstract_dist = self._get_abstract_dist_for(req_to_install)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
updater | <job_17502186>     req, self.session, self.finder, self.require_hashes
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
updater | <job_17502186>     req, self.req_tracker, finder, self.build_isolation,
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
updater | <job_17502186>     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
updater | <job_17502186>     self.req.prepare_metadata()
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
updater | <job_17502186>     self.metadata_directory = metadata_generator(self)
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
updater | <job_17502186>     command_desc='python setup.py egg_info',
updater | <job_17502186>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
updater | <job_17502186>     raise InstallationError(exc_msg)
updater | <job_17502186> pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by bryanculbertson** [comment]
I reported this error in `rtree`, and the maintainer making sure you are specifying the location of `libspatialindex` correctly. https://github.com/Toblerity/rtree/issues/135
