### ISSUE TITLE
Dependabot is giving a time_out error

### ISSUE THREAD

**Issue by calculuschild** [dependabot/feedback#840]
Just started trying to use Dependabot today and after about 20 minutes (which seems really really slow...) it finally changes the status from "checking now, hold tight!" to "checked 2 minutes ago" but no PRs are created. I look at the logs and see that it has a `timed_out` status and several errors.

The log is attached here:
```
 proxy | time="2020-02-03T17:01:52Z" level=info msg="proxy starting" commit=c112a5a5cd86983046156e55becbc0d14ef9cb3e
  proxy | 2020/02/03 17:01:52 Listening (:1080)
fetcher | yarn config v1.21.1
fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
fetcher | Done in 0.03s.
fetcher | INFO <job_22326270> Starting job processing
fetcher | ERROR <job_22326270> Error during file fetching; aborting
fetcher | ERROR <job_22326270> missing keyword: security_updates_only
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:73:in `file_fetcher'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:63:in `base_commit_sha'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | ERROR <job_22326270> bin/fetch_files.rb:21:in `<main>'
fetcher | ERROR <job_22326270> missing keyword: security_updates_only
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:122:in `handle_file_fetcher_error'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:15:in `rescue in perform_job'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:10:in `perform_job'
fetcher | ERROR <job_22326270> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | ERROR <job_22326270> bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:40:in `handle_exception'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:32:in `rescue in run'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:27:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:122:in `handle_file_fetcher_error'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:15:in `rescue in perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:10:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:73:in `file_fetcher'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:63:in `base_commit_sha'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
```

My public repository is here: [homebrewery](https://github.com/naturalcrit/homebrewery)

Any idea what's going on?

**Comment by calculuschild** [comment]
Looks like a fix was already [deployed](https://github.com/dependabot/dependabot-core/issues/1672) but it doesn't seem to be live. When can we expect this fix to come around?

**Comment by feelepxyz** [comment]
@calculuschild this should be fixed on your repository 👍 sorry for the slow reply!
